#pragma once
// -----------------------------------------------------------------------------
//  FontTr - an 8x16 bitmap font that can spell Turkish.
//
//  Every font M5GFX ships is either ASCII only (Font0, Font2 and all the
//  FreeSans and DejaVu families stop at 0x7E) or a CJK font whose source is
//  between seventeen and thirty-three megabytes. Neither can write "yagmur
//  yagiyor" with the right letters in it.
//
//  Turkish needs twelve characters. Six of them (C-cedilla, O and U with
//  diaeresis and their lowercase) exist in Latin-1, and CP437 has drawings of
//  them; the other six, G-breve, S-cedilla, dotted and dotless I, are Latin
//  Extended-A and are in neither.
//
//  So all twelve are composed from CP437's own ASCII letters plus one shared
//  set of marks. That also fixes something using CP437's accented glyphs would
//  not: those are redrawn, compressed letterforms rather than the plain letter
//  with a mark on it, so "cicek" written with CP437's c-cedilla shows two
//  different c's in one word.
//
//  1.9 KB of data, generated by tools/make_tr_font.py, which prints any glyph
//  as ASCII art so a mark can be placed by looking rather than by guessing.
// -----------------------------------------------------------------------------
#include <M5Unified.h>

namespace sd::ui {

/// Fixed 8x16. Pass it to any Canvas text call; M5GFX decodes UTF-8 itself, so
/// a note stored as UTF-8 draws without anything in between.
extern const lgfx::BDFfont FontTr;

}  // namespace sd::ui
