// GENERATED by tools/make_tr_font.py - do not edit by hand.
//
// ASCII 0x20-0x7E lifted from M5GFX's CP437 8x16 bitmap (Fonts/Ascii8x16.h),
// plus twelve Turkish letters composed from those same bases. See the script
// for why CP437's own accented glyphs are not used and how each mark is placed.
#pragma once
#include <cstdint>

namespace sd {

/// The non-ASCII codepoints the panel font can draw, sorted.
///
/// Emitted from the same table that builds the font, because a note may only
/// keep a character the device can show. The two lists disagreeing means text
/// stored as typed and drawn as a row of boxes.
constexpr uint16_t kNoteExtraCp[] = {
    0x00C7, 0x00D6, 0x00DC, 0x00E7, 0x00F6, 0x00FC, 0x011E, 0x011F, 0x0130, 0x0131, 0x015E, 0x015F,
};
constexpr int kNoteExtraCount =
    static_cast<int>(sizeof(kNoteExtraCp) / sizeof(kNoteExtraCp[0]));

}  // namespace sd
